#if BROWSER
using Examples;
namespace Examples.Textures;

public partial class RawData : IExample
{
    private readonly BrowserAdapter _browserAdapter = new();

    public string Name => _browserAdapter.Name;

    public void Init()
    {
        _browserAdapter.Init();
    }

    public void Update()
    {
        _browserAdapter.Update();
    }

    public void Unload()
    {
        _browserAdapter.Unload();
    }

    private unsafe sealed class BrowserAdapter : IExample
    {
        public string Name => "Textures / Raw Data";

        private const int screenWidth = 800;
        private const int screenHeight = 450;

        private Texture2D _fudesumi;
        private Texture2D _checkedTex;

        public void Init()
        {
            // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

            // Load RAW image data (512x512, 32bit RGBA, no file header)
            Image fudesumiRaw = LoadImageRaw(
                "resources/fudesumi.raw",
                384,
                512,
                PixelFormat.UncompressedR8G8B8A8,
                0
            );
            _fudesumi = LoadTextureFromImage(fudesumiRaw);
            UnloadImage(fudesumiRaw);

            // Generate a checked texture by code
            int imWidth = 960;
            int imHeight = 480;

            // Dynamic memory allocation to store pixels data (Color type)
            // WARNING: Using raylib provided MemAlloc() that uses default raylib
            // internal memory allocator, so this data can be freed using UnloadImage()
            // that also uses raylib internal memory de-allocator
            Color* pixels = (Color*)MemAlloc((uint)(imWidth * imHeight * sizeof(Color)));

            for (int y = 0; y < imHeight; y++)
            {
                for (int x = 0; x < imWidth; x++)
                {
                    if (((x / 32 + y / 32) / 1) % 2 == 0)
                    {
                        pixels[y * imWidth + x] = Color.Orange;
                    }
                    else
                    {
                        pixels[y * imWidth + x] = Color.Gold;
                    }
                }
            }

            // Load pixels data into an image structure and create texture
            // NOTE: We can assign pixels directly to data because Color is R8G8B8A8
            // data structure defining that pixelformat, format must be set properly
            Image checkedIm = new Image
            {
                Data = pixels,
                Width = imWidth,
                Height = imHeight,
                Format = PixelFormat.UncompressedR8G8B8A8,
                Mipmaps = 1,
            };
            _checkedTex = LoadTextureFromImage(checkedIm);
            MemFree(pixels);
        }

        public void Update()
        {
            BeginDrawing();
            ClearBackground(Color.RayWhite);

            int x = screenWidth / 2 - _checkedTex.Width / 2;
            int y = screenHeight / 2 - _checkedTex.Height / 2;
            DrawTexture(_checkedTex, x, y, Fade(Color.White, 0.5f));
            DrawTexture(_fudesumi, 430, -30, Color.White);

            DrawText("CHECKED TEXTURE ", 84, 85, 30, Color.Brown);
            DrawText("GENERATED by CODE", 72, 148, 30, Color.Brown);
            DrawText("and RAW IMAGE LOADING", 46, 210, 30, Color.Brown);

            DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, Color.Brown);

            EndDrawing();
        }

        public void Unload()
        {
            UnloadTexture(_fudesumi);
            UnloadTexture(_checkedTex);
        }
    }
}
#endif
