// Adapted for the browser from Examples/Textures/RawData.cs
namespace Examples.Web;

public unsafe class TexturesRawData : IWebExample
{
    public string Name => "Textures / Raw Data";

    private const int ScreenWidth = 960;
    private const int ScreenHeight = 540;

    private Texture2D _fudesumi;
    private Texture2D _checkedTex;

    public void Init()
    {
        // NOTE: Textures MUST be loaded after Window initialization (OpenGL context is required)

        // Load RAW image data (512x512, 32bit RGBA, no file header)
        Image fudesumiRaw = LoadImageRaw(
            "resources/fudesumi.raw",
            384,
            512,
            PixelFormat.UncompressedR8G8B8A8,
            0
        );
        _fudesumi = LoadTextureFromImage(fudesumiRaw);
        UnloadImage(fudesumiRaw);

        // Generate a checked texture by code
        int width = 960;
        int height = 480;

        // Store pixel data
        Color* pixels = (Color*)MemAlloc((uint)(width * height * sizeof(Color)));
        for (int y = 0; y < height; y++)
        {
            for (int x = 0; x < width; x++)
            {
                if (((x / 32 + y / 32) / 1) % 2 == 0)
                {
                    pixels[y * width + x] = Color.Orange;
                }
                else
                {
                    pixels[y * width + x] = Color.Gold;
                }
            }
        }

        // Load pixels data into an image structure and create texture
        Image checkedIm = new Image
        {
            Data = pixels,
            Width = width,
            Height = height,
            Format = PixelFormat.UncompressedR8G8B8A8,
            Mipmaps = 1,
        };
        _checkedTex = LoadTextureFromImage(checkedIm);
        MemFree(pixels);
    }

    public void Update()
    {
        BeginDrawing();
        ClearBackground(Color.RayWhite);

        int x = ScreenWidth / 2 - _checkedTex.Width / 2;
        int y = ScreenHeight / 2 - _checkedTex.Height / 2;
        DrawTexture(_checkedTex, x, y, ColorAlpha(Color.White, 0.5f));
        DrawTexture(_fudesumi, 430, -30, Color.White);

        DrawText("CHECKED TEXTURE ", 84, 85, 30, Color.Brown);
        DrawText("GENERATED by CODE", 72, 148, 30, Color.Brown);
        DrawText("and RAW IMAGE LOADING", 46, 210, 30, Color.Brown);

        DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, ScreenHeight - 20, 10, Color.Brown);

        EndDrawing();
    }

    public void Unload()
    {
        UnloadTexture(_fudesumi);
        UnloadTexture(_checkedTex);
    }
}
